//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public string SubID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
