//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public string WithdrawalID { get; set; }
        public string WalletID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Wallet Wallet { get; set; }
    }
}
